version: '3.7'

services:
  mongo:
    image: mongo
    container_name: database
    restart: always
    environment: 
      MONGODB_USER: "${db_user_env}"
      MONGODB_DATABASE: "${dbname_env}"
      MONGODB_PASS: "${db_pass}"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  client:
    stdin_open: true
    tty: true
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    ports:
      - 3000:3000
    depends_on: 
      - server
    volumes: 
      - uploads:/server/uploads

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment: 
      DATABASE_URL: mongodb://@mongo:27017/
    restart: always
    container_name: server
    ports: 
      - 4000:4000
    depends_on: 
      - mongo

volumes:
  mongodb_data:
    driver: local
  img:
    driver: local