version: '3.7'

services:
  mongo:
    image: mongo
    container_name: database
    restart: always
    environment: 
      MONGODB_USER: admin
      MONGODB_DATABASE: mongo
      MONGODB_PASS: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  client:
    stdin_open: true
    tty: true
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    ports:
      - 3000:3000
    depends_on: 
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment: 
      DATABASE_URL: mongodb://@mongo:27017/
    restart: always
    container_name: server
    ports: 
      - 4000:4000
    depends_on: 
      - mongo
    volumes: 
      - ./server/uploads:/usr/server/uploads

volumes:
  mongodb_data:
    driver: local